export function getVSCodeKeybindings(monaco: typeof import('monaco-editor')) {
  const KeyChord = (monaco as any).KeyChord as (first: number, second: number) => number
  return [
    { id: 'editor.action.addSelectionToNextFindMatch', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyD },
    { id: 'editor.action.insertCursorAbove', key: monaco.KeyMod.CtrlCmd | monaco.KeyMod.Alt | monaco.KeyCode.UpArrow },
    { id: 'editor.action.insertCursorBelow', key: monaco.KeyMod.CtrlCmd | monaco.KeyMod.Alt | monaco.KeyCode.DownArrow },
    { id: 'editor.action.selectHighlights', key: monaco.KeyMod.CtrlCmd | monaco.KeyMod.Shift | monaco.KeyCode.KeyL },
    { id: 'editor.action.deleteLines', key: monaco.KeyMod.CtrlCmd | monaco.KeyMod.Shift | monaco.KeyCode.KeyK },
    { id: 'editor.action.deleteWordLeft', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.Backspace },
    { id: 'editor.action.deleteWordRight', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.Delete },
    { id: 'editor.action.insertLineBefore', key: monaco.KeyMod.CtrlCmd | monaco.KeyMod.Shift | monaco.KeyCode.Enter },
    { id: 'editor.action.insertLineAfter', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter },
    { id: 'editor.action.moveLinesUpAction', key: monaco.KeyMod.Alt | monaco.KeyCode.UpArrow },
    { id: 'editor.action.moveLinesDownAction', key: monaco.KeyMod.Alt | monaco.KeyCode.DownArrow },
    { id: 'editor.action.copyLinesUpAction', key: monaco.KeyMod.Alt | monaco.KeyMod.Shift | monaco.KeyCode.UpArrow },
    { id: 'editor.action.copyLinesDownAction', key: monaco.KeyMod.Alt | monaco.KeyMod.Shift | monaco.KeyCode.DownArrow },
    { id: 'editor.action.commentLine', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.Slash },
    { id: 'editor.action.blockComment', key: monaco.KeyMod.CtrlCmd | monaco.KeyMod.Shift | monaco.KeyCode.Slash },
    { id: 'editor.action.outdent', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.BracketLeft },
    { id: 'editor.action.indent', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.BracketRight },
    { id: 'editor.action.revealDefinition', key: monaco.KeyCode.F12 },
    { id: 'editor.action.peekDefinition', key: monaco.KeyMod.Alt | monaco.KeyCode.F12 },
    { id: 'editor.action.revealTypeDefinition', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.F12 },
    { id: 'editor.action.referenceSearch.trigger', key: monaco.KeyMod.Shift | monaco.KeyCode.F12 },
    { id: 'editor.action.jumpToBracket', key: monaco.KeyMod.CtrlCmd | monaco.KeyMod.Shift | monaco.KeyCode.Backslash },
    { id: 'editor.action.rename', key: monaco.KeyCode.F2 },
    { id: 'editor.action.formatDocument', key: monaco.KeyMod.Shift | monaco.KeyMod.Alt | monaco.KeyCode.KeyF },
    { id: 'editor.action.formatSelection', key: KeyChord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyK, monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyF) },
    { id: 'editor.action.startFindReplaceAction', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyH },
    { id: 'editor.action.cursorUndo', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyU },
    { id: 'editor.action.quickFix', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.Period },
    { id: 'editor.action.nextMatchFindAction', key: monaco.KeyCode.F3 },
    { id: 'editor.action.previousMatchFindAction', key: monaco.KeyMod.Shift | monaco.KeyCode.F3 },
    { id: 'editor.foldAll', key: KeyChord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyK, monaco.KeyMod.CtrlCmd | monaco.KeyCode.Digit0) },
    { id: 'editor.unfoldAll', key: KeyChord(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyK, monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyJ) },
    { id: 'editor.foldLevel1', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.Digit1 },
    { id: 'editor.foldLevel2', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.Digit2 },
    { id: 'editor.foldLevel3', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.Digit3 },
    { id: 'editor.foldRecursively', key: monaco.KeyMod.CtrlCmd | monaco.KeyMod.Alt | monaco.KeyCode.BracketLeft },
    { id: 'editor.unfoldRecursively', key: monaco.KeyMod.CtrlCmd | monaco.KeyMod.Alt | monaco.KeyCode.BracketRight },
    { id: 'editor.fold', key: monaco.KeyMod.CtrlCmd | monaco.KeyMod.Shift | monaco.KeyCode.BracketLeft },
    { id: 'editor.unfold', key: monaco.KeyMod.CtrlCmd | monaco.KeyMod.Shift | monaco.KeyCode.BracketRight },
    { id: 'editor.action.smartSelect.expand', key: monaco.KeyMod.Shift | monaco.KeyMod.Alt | monaco.KeyCode.RightArrow },
    { id: 'editor.action.smartSelect.shrink', key: monaco.KeyMod.Shift | monaco.KeyMod.Alt | monaco.KeyCode.LeftArrow },
    { id: 'editor.action.expandLineSelection', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyL },
    { id: 'editor.action.addCursorsToLineEnds', key: monaco.KeyMod.Shift | monaco.KeyMod.Alt | monaco.KeyCode.KeyI },
    { id: 'editor.action.addSelectionToPreviousFindMatch', key: monaco.KeyMod.CtrlCmd | monaco.KeyMod.Shift | monaco.KeyCode.KeyD },
    { id: 'editor.action.changeAll', key: monaco.KeyMod.CtrlCmd | monaco.KeyCode.F2 },
    { id: 'editor.action.selectToBracket', key: monaco.KeyMod.CtrlCmd | monaco.KeyMod.Shift | monaco.KeyMod.Alt | monaco.KeyCode.Backslash },
  ] as { id: string; key: number }[]
}
